//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika3_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_Good { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
